AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 2
Resources:
  DevPing:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs14.x
      CodeUri: ../../built/dev/ping
      Handler: index.handler
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /ping
            Method: get
