AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 2
  Api:
    OpenApiVersion: 3.0.2
Resources:
  UniLambdaBasicApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: "'WWW-Authenticate'"
              Access-Control-Allow-Origin: "'*'"
  UniPingFunc:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs14.x
      Role: arn:aws:iam::260006775748:role/lambda-basic-role
      Policies:
        - Version: "2012-10-17"
          Statement: 
          - Effect: "Allow"
            Action: 
              - "s3:GetObject"
            Resource: [
                "arn:aws:s3:::uni-lambda-dev/*",
                "arn:aws:s3:::uni-lambda-dev"
            ]
      CodeUri: s3://uni-lambda-dev/lambda-typescript-deploy/typescript-deploy/built/dev/ping/index.js
      Handler: index.handler
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /ping
            Method: get
            RestApiId: !Ref UniLambdaBasicApi
