version: 0.2

phases:
  pre_build:
    commands:
      - cd typescript-deploy
  build:
    commands:
      - npm install
      - npm run build-dev
      - aws cloudformation package --template-file ./sam/dev/template.yaml --s3-bucket uni-lambda-dev  --s3-prefix sam/aws-lambda-basic/dev/package --output-template-file template.yaml --capabilities CAPABILITY_IAM
      - aws cloudformation deploy --template-file ./sam/dev/template.yaml --stack-name lambda-typescript-deploy
  post_build:
    commands:
      - echo done!
artifacts:
  files:
    - typescript-deploy/built/dev/ping/index.js